#!/bin/bash

# Author : Moebius2722
# Mail : moebius2722@laposte.net
# Git : https://github.com/Moebius2722/ElkPi.git

# Full Automated Remote SSH for All Elasticsearch Nodes on Raspberry Pi 2 or 3


####### ALLSSH #######

iphost=`hostname -i`
ipnodes=( `sudo cat /etc/elasticsearch/discovery-file/unicast_hosts.txt | grep -e '^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' | grep -v $iphost | sort` )
for ipnode in "${ipnodes[@]}"
do
  echo "================================================================================"
  echo "START : ssh $ipnode $*"
  echo "================================================================================"
  echo
  ssh $ipnode $*
  errorcmd=$?
  echo
  echo "================================================================================"
  echo "RETURN : $errorcmd"
  echo "================================================================================"
  echo
done
echo "================================================================================"
echo "START : ssh $iphost $*"
echo "================================================================================"
echo
ssh $iphost $*
errorcmd=$?
echo
echo "================================================================================"
echo "RETURN : $errorcmd"
echo "================================================================================"
echo
