#!/bin/bash

# Author : Moebius2722
# Mail : moebius2722@laposte.net
# Git : https://github.com/Moebius2722/ElkPi.git

# Full Automated Remote SSH for All Elasticsearch Nodes on Raspberry Pi 2 or 3


####### ALLSSH #######

ipnodes=( `sudo cat /etc/elasticsearch/discovery-file/unicast_hosts.txt | grep -e '^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' | sort` )
for ipnode in "${ipnodes[@]}"
do
  ssh $ipnode $*
done
